server:
port: 52001
servlet:
  context-path: /
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  datasource:
        driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://posgre.postgres.database.azure.com:5432/projectaction?sslmode=require
    username: samba
    password: Douldoul1

  jwt:
    secret: projectActionSecretKey
    expirationMs: 86400000
